include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [
    build/**,
    lib/**.g.dart,
    test/test_config/hive/hive_common.dart,
  ]

linter:
  rules:
    sort_pub_dependencies: false
    require_trailing_commas: false
    avoid_catching_errors: false
