name: localchess
description: A new Flutter project.
publish_to: 'none'
version: 0.2.1+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chess: ^0.8.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.9
  network_info_plus: ^4.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bishop.svg
    - assets/images/king.svg
    - assets/images/knight.svg
    - assets/images/pawn.svg
    - assets/images/queen.svg
    - assets/images/rok.svg
