name: localchess
description: A Flutter chess application for playing locally on a single device or across two devices over a local network.

publish_to: 'none'
version: 2.0.1+20

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Local Modules
  core:
    path: module/core
  gen:
    path: module/gen
  widget:
    path: module/widget

  # Utilities & Helpers
  async: ^2.11.0
  chess: ^0.8.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  get_it: ^9.2.1
  logger: ^2.7.0
  url_launcher: ^6.3.2
  uuid: ^4.4.2

  # State Management
  flutter_bloc: ^8.1.6

  # Navigation
  auto_route: ^11.1.0

  # UI & Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Analysis & Generators
  auto_route_generator: ^10.5.0
  bloc_test: ^9.1.7
  very_good_analysis: ^10.3.0

  # Testing
  shared_preferences: any

flutter:
  uses-material-design: true

  assets:
    - asset/translation/
