name: widget
description: "A new Flutter package project."
version: 0.0.1
homepage: 'none'

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
